#!/bin/bash
# CS 302, assignment #8 test script.

# ---------------------------------------------------------
# Initial checks.
#	Ensure executable file exists.

if [ -z $1 ]; then
	echo "Error, must provide executable file name."
	exit
fi

if [ ! -e $1 ] || [ ! -x $1 ]; then
	echo "Error, unable to find $1 executable file."
	exit
fi

# ---------------------------------------------------------
# Define script variables and function

bolded=`tput bold`
normal=`tput sgr0`
bldred=`tput bold``tput setaf 1`

pause() {
	if [ "$1" = "skip" ]; then
		echo
	else
		echo
		echo -n "Press return to continue"
		read
		clear
	fi
}

# ---------------------------------------------------------
# Display initial page

clear
echo
echo
echo ${bolded}Assignment 8 - Testing Utility${normal}
echo
echo
echo
echo
echo "Note, this utility assumes the program is working or very"
echo "      close to working.  Testing on an incomplete"
echo "      program will not be useful."
echo
echo
echo
#
# ---------------------------------------------------------
#
pause $2
#
# ---------------------------------------------------------
# Begin tests.
#
# ---------------------------------
#  PQ Testing
echo
echo "**********************************************************************"
echo ${bolded}Priority Queue Test Program...${normal}
echo
echo
echo
echo
./pqTest > testOut.txt

if `diff testOut.txt mstrPQtest.txt >/dev/null` ; then
	echo "PQ Test Successful"
else
	diff testOut.txt mstrPQtest.txt
fi
echo
echo
echo
echo
pause $2
#
# ---------------------------------
#  testing
#
echo "**********************************************************************"
echo ${bolded}Execution Testing...${normal}
echo
echo ${bolded}./$1 ${normal}
./$1 > out.txt
#
if `diff <(head -n 39 out.txt) <(head -n 39 mstr.txt) >/dev/null` ; then
	echo "Test Successful"
else
	echo "Test Unsuccessful"
	echo
	diff <(head -n 39 out.txt) <(head -n 39 mstr.txt)
fi
#
echo
echo
echo

